### PR TITLE
Cleanup old code related to end2end tests

### PR DESCRIPTION
**Pull request by keymon**
All the smoke and end2end tests [have been moved to tsuru-ansible](https://github.com/alphagov/tsuru-ansible/pull/93). This repository will keep other tests (integration, acceptance). This commit deletes the old code, so we can continue working in clean repository.

### CODE REVIEW

**Comment by dcarley** [comment]
Shouldn't the other tests also be moved to tsuru-ansible?

**Comment by keymon** [comment]
Yes, maybe. The issue is that why should be in tsuru-ansible, if the tests might be a integration one might requires use terraform? On the other hand, makes sense keep all in the same repository.

Any option is fine for me.

**Comment by dcarley** [comment]
I think we should move them to tsuru-ansible because:
- we're more likey to change integration tests at the same time as changing Ansible code
- it saves us duplicating some of the rspec meta-setup-stuff

We can break them out at a later date if it becomes necessary.

**Comment by keymon** [comment]
OK,

In that case I propose merge this PR and we will move the rest later.

On 14 July 2015 at 12:36, Dan Carley notifications@github.com wrote:

> I think we should move them to tsuru-ansible because:
> - we're more likey to change integration tests at the same time as
>   changing Ansible code
> - it saves us duplicating some of the rspec meta-setup-stuff
> 
> We can break them out at a later date if it becomes necessary.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alphagov/tsuru-testing/pull/1#issuecomment-121210750.

## 

Regards
Hector Rivas | GDS / Multi-Cloud PaaS

**Comment by dcarley** [comment]
:+1:

**Pull request merged**
